# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies (skip any prepare scripts if necessary)
RUN npm install --ignore-scripts

# Copy rest of the files and build
COPY . .
RUN npm run build

# Expose any port if necessary (assuming 3000 for development inspection, but sonic-pi might not require it)
EXPOSE 3000

# Start the server
CMD ["npm", "start"]
