# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM oven/bun:latest

WORKDIR /app

# Copy package files
COPY package.json bun.lock ./

# Install dependencies
RUN bun install

# Copy rest of the files
COPY . .

# Build if needed
RUN bun run build

# Expose UDP port for OSC communication
EXPOSE 4560/udp

# Start the server using bun
CMD ["bun", "src/server.ts"]
