# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM oven/bun:latest

WORKDIR /app

# Copy package files
COPY package.json bun.lock ./

# Install dependencies
RUN bun install

# Copy rest of the files
COPY . .

# We don't need to expose port 3000 as we're using OSC on 4560
# Instead, we need to ensure UDP communication is possible for OSC
EXPOSE 4560/udp

# Start the server using bun
CMD ["bun", "run", "src/server.ts"]
